name: NuGet Push
description: An opinionated action that downloads existing NuGet packages and pushes them to a package source and publishes them.
inputs:
  source:
    description: The NuGet Server URL.
    required: true
    default: 'https://api.nuget.org/v3/index.json'
  token:
    description: The NuGet API key.
    required: true
  configuration:
    description: Defines the build configuration. Default is Release.
    required: true
    default: 'Release'
  level:
    description: Sets the verbosity level of the command. Allowed values are quiet, normal and detailed. The default is quiet.
    required: true
    default: 'quiet'
runs:
  using: composite
  steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        name: NuGet-${{ inputs.configuration }}

    - name: Display structure of downloaded files
      run: |
        pwd
        ls -R
      shell: bash

    - name: NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: latest
        nuget-api-key: ${{ inputs.token }}

    - name: Push
      run: nuget push '${{ github.workspace }}/*.nupkg' -Source ${{ inputs.source }} -SkipDuplicate -Verbosity ${{ inputs.level }}
      shell: bash
branding:
  icon: 'umbrella'
  color: 'blue'
